import os


class Config:
	RENDER_SERVICE_PORT = os.getenv('RENDER_SERVICE_PORT')
	DITTO_DATA_ROOT = os.getenv('DITTO_DATA_ROOT')
	ONLINE_STREAMING_TIMESTAMPS = os.getenv('ONLINE_STREAMING_TIMESTAMPS')
	ONLINE_RENDER_TIMESTAMPS = os.getenv('ONLINE_RENDER_TIMESTAMPS')
	QUEUE_MAX_SIZE = os.getenv('QUEUE_MAX_SIZE')
	MS_MAX_SIZE = os.getenv('MS_MAX_SIZE')
	A2M_MAX_SIZE = os.getenv('A2M_MAX_SIZE')
	LOG_LEVEL = os.getenv('LOG_LEVEL')
	MAX_SIZE = os.getenv('MAX_SIZE')
	WEIGHTS_PATH = os.getenv('WEIGHTS_PATH')
