# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import rtc_mediaserver.proto.render_service_pb2 as render__service__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in render_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RenderServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RenderStream = channel.stream_stream(
                '/Render.RenderService/RenderStream',
                request_serializer=render__service__pb2.RenderRequest.SerializeToString,
                response_deserializer=render__service__pb2.RenderResponse.FromString,
                _registered_method=True)
        self.InfoRouter = channel.unary_unary(
                '/Render.RenderService/InfoRouter',
                request_serializer=render__service__pb2.InfoRequest.SerializeToString,
                response_deserializer=render__service__pb2.InfoResponse.FromString,
                _registered_method=True)


class RenderServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RenderStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InfoRouter(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RenderServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RenderStream': grpc.stream_stream_rpc_method_handler(
                    servicer.RenderStream,
                    request_deserializer=render__service__pb2.RenderRequest.FromString,
                    response_serializer=render__service__pb2.RenderResponse.SerializeToString,
            ),
            'InfoRouter': grpc.unary_unary_rpc_method_handler(
                    servicer.InfoRouter,
                    request_deserializer=render__service__pb2.InfoRequest.FromString,
                    response_serializer=render__service__pb2.InfoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Render.RenderService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Render.RenderService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RenderService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RenderStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/Render.RenderService/RenderStream',
            render__service__pb2.RenderRequest.SerializeToString,
            render__service__pb2.RenderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InfoRouter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Render.RenderService/InfoRouter',
            render__service__pb2.InfoRequest.SerializeToString,
            render__service__pb2.InfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
